// create a prompt system that keeps prompting user for a number
// the num is generated byy math random
// if the num is right tell them and how many guesses it took

// if the num is wrong tell them if it is higher or lower

let guess = prompt("Guess a number between 1 and 10");
let num = Math.floor(Math.random() * 10) + 1;
let counter = 1;
while (guess != num) {
    if (guess > num) {
        alert("Too High");
    } else {
        alert("Too Low");
    }
    guess = prompt("Guess a number between 1 and 10");
    counter++;
}
alert("You got it in " + counter + " guesses!");